### PR TITLE
fix issue #22 switch cooperative error

### PR DESCRIPTION
**Pull request by fdgenie**
Cooperative switch now doesn't disappear

### CODE REVIEW

**Comment by DavidGolodetsky** [comment]
Oh, great. But I should be more specific on that. I want switcher to be there, but those two fields to be hidden (if it switched on). Cause those fields make sense only  in multiplayer game.

image

**Comment by DavidGolodetsky** [comment]
btw, if you're so into that project I can invite you to my trello board where I manage it. There are a lot more then those issues:)

**Comment by fdgenie** [comment]
Ok im on it, but i think that there is still point for those two fields to exist, because it maybe be cooperative but beside the team name you may still want to keep info of how many players and which players the team consist of.
Sure why not, invite me if you want.

**Comment by DavidGolodetsky** [comment]
Waaait) I mixed cooperative with solo game:)

**Comment by DavidGolodetsky** [comment]
You're right. Info about team players should be there. But the thing is that if you specify players, you can mess up rounds board

**Comment by fdgenie** [comment]
I think now its ok then :)

**Comment by DavidGolodetsky** [comment]
Ah, it's fine. I've just checked cooperative + specified players. One thing though: I would remove this option for cooperative games. What do you think?

image

**Comment by DavidGolodetsky** [comment]
What's your email so I could invite you to trello?

**Comment by fdgenie** [comment]
pa.aris@yahoo.gr

**Comment by DavidGolodetsky** [comment]
done. welcome aboard:)

**Pull request merged**
