### PR TITLE
Dockerize the app and adapt readme.md

### PR DESCRIPTION
**Pull request by Rayleigh3105**
Hope everything is working fine. Also let me know if there must be done some changes.

### CODE REVIEW

**Comment by DavidGolodetsky** [comment]
Great! Thank you! Going to check it out

**Comment by DavidGolodetsky** [comment]
So I need to run something like `docker-compose build`?

**Comment by DavidGolodetsky** [comment]
Could you provide a rough documentation on that?

**Comment by Rayleigh3105** [comment]
The documentation is located in the readme.md file. 
- When running the app with not existing docker images run **docker-compose up --build**
- When running the app with existing images run **docker-compose up**

**Comment by DavidGolodetsky** [comment]
oh it's already there, I overlooked it. thanx!

**Comment by DavidGolodetsky** [comment]
I got to say, it's the best Hacktoberfest PR so far! I'd like to know more about docker, maybe you could recommend me some tutorial?

**Comment by Rayleigh3105** [comment]
Glad to hear that, it's just like learning everything else, do it and google it. But I can recommend a Book about Docker -> https://www.amazon.de/Docker-Praxisbuch-Entwickler-DevOps-Teams-Windows/dp/3836272261/ref=sr_1_5?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=docker&qid=1602071578&sr=8-5 I think it is only available in German language. If you have any Frontend or Backend Task´s to do. I would also have a look at this. That´s the first Project where I'm in contact with vue.js.

**Comment by DavidGolodetsky** [comment]
thanx! well, I don't know German:) yeah, I'm planning to create a couple of new issues in order to extend functionality, also In the future I'm planning to rewrite the whole app with Vue.js 3. I'm frontend developer, it's my first experience as a fullstack, so my backend is loosy:) If you find anything that worth to improve (like you did with .env - great feature), I'd be glad. About authenication I'm planning to rewrite it with jwt token, cause now it's using firebase-auth. Also you can join the project as a maintainer if you want and suggest your view of the app, and where it should go. There is another guy who is interested in developing the app as well, so it's kinda a team:)

**Pull request merged**
