### PR TITLE
Added route to get win rate with game id.

### PR DESCRIPTION
**Pull request by Thunder80**
Added a route in routes/api/games.js to get the win rate from a given game id.

### CODE REVIEW

**Comment by DavidGolodetsky** [comment]
That's awesome! I'll try to implement UI part today and deploy so you could see result of your work in action. Thanx!

**Comment by Thunder80** [comment]
Yea will be waiting for that.😀😀😀

**Comment by DavidGolodetsky** [comment]
It's alive) Great feature, thanx again
image

**Comment by Thunder80** [comment]
O great to see it in action!!!!

**Pull request merged**
